package com.dhsy.async.entity;

import java.util.Date;

public class PointFlow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_flow.number
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_flow.sheetName
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    private String sheetname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_flow.memName
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    private String memname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_flow.memCard
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    private String memcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_flow.createTime
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_flow.bizName
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    private String bizname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_flow.memMobile
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    private String memmobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_flow.occurPoints
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    private Long occurpoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_flow.points
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    private Long points;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_flow.direction
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    private String direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_flow.status
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    private Integer status = 0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_flow.number
     *
     * @return the value of point_flow.number
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public PointFlow withNumber(String number) {
        this.setNumber(number);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_flow.number
     *
     * @param number the value for point_flow.number
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_flow.sheetName
     *
     * @return the value of point_flow.sheetName
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String getSheetname() {
        return sheetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public PointFlow withSheetname(String sheetname) {
        this.setSheetname(sheetname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_flow.sheetName
     *
     * @param sheetname the value for point_flow.sheetName
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public void setSheetname(String sheetname) {
        this.sheetname = sheetname == null ? null : sheetname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_flow.memName
     *
     * @return the value of point_flow.memName
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String getMemname() {
        return memname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public PointFlow withMemname(String memname) {
        this.setMemname(memname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_flow.memName
     *
     * @param memname the value for point_flow.memName
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public void setMemname(String memname) {
        this.memname = memname == null ? null : memname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_flow.memCard
     *
     * @return the value of point_flow.memCard
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String getMemcard() {
        return memcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public PointFlow withMemcard(String memcard) {
        this.setMemcard(memcard);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_flow.memCard
     *
     * @param memcard the value for point_flow.memCard
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public void setMemcard(String memcard) {
        this.memcard = memcard == null ? null : memcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_flow.createTime
     *
     * @return the value of point_flow.createTime
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public PointFlow withCreatetime(Date createtime) {
        this.setCreatetime(createtime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_flow.createTime
     *
     * @param createtime the value for point_flow.createTime
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_flow.bizName
     *
     * @return the value of point_flow.bizName
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String getBizname() {
        return bizname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public PointFlow withBizname(String bizname) {
        this.setBizname(bizname);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_flow.bizName
     *
     * @param bizname the value for point_flow.bizName
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public void setBizname(String bizname) {
        this.bizname = bizname == null ? null : bizname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_flow.memMobile
     *
     * @return the value of point_flow.memMobile
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String getMemmobile() {
        return memmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public PointFlow withMemmobile(String memmobile) {
        this.setMemmobile(memmobile);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_flow.memMobile
     *
     * @param memmobile the value for point_flow.memMobile
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public void setMemmobile(String memmobile) {
        this.memmobile = memmobile == null ? null : memmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_flow.occurPoints
     *
     * @return the value of point_flow.occurPoints
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public Long getOccurpoints() {
        return occurpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public PointFlow withOccurpoints(Long occurpoints) {
        this.setOccurpoints(occurpoints);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_flow.occurPoints
     *
     * @param occurpoints the value for point_flow.occurPoints
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public void setOccurpoints(Long occurpoints) {
        this.occurpoints = occurpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_flow.points
     *
     * @return the value of point_flow.points
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public Long getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public PointFlow withPoints(Long points) {
        this.setPoints(points);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_flow.points
     *
     * @param points the value for point_flow.points
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public void setPoints(Long points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_flow.direction
     *
     * @return the value of point_flow.direction
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public PointFlow withDirection(String direction) {
        this.setDirection(direction);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_flow.direction
     *
     * @param direction the value for point_flow.direction
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_flow.status
     *
     * @return the value of point_flow.status
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public PointFlow withStatus(Integer status) {
        this.setStatus(status);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_flow.status
     *
     * @param status the value for point_flow.status
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PointFlow other = (PointFlow) that;
        return (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getSheetname() == null ? other.getSheetname() == null : this.getSheetname().equals(other.getSheetname()))
            && (this.getMemname() == null ? other.getMemname() == null : this.getMemname().equals(other.getMemname()))
            && (this.getMemcard() == null ? other.getMemcard() == null : this.getMemcard().equals(other.getMemcard()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getBizname() == null ? other.getBizname() == null : this.getBizname().equals(other.getBizname()))
            && (this.getMemmobile() == null ? other.getMemmobile() == null : this.getMemmobile().equals(other.getMemmobile()))
            && (this.getOccurpoints() == null ? other.getOccurpoints() == null : this.getOccurpoints().equals(other.getOccurpoints()))
            && (this.getPoints() == null ? other.getPoints() == null : this.getPoints().equals(other.getPoints()))
            && (this.getDirection() == null ? other.getDirection() == null : this.getDirection().equals(other.getDirection()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getSheetname() == null) ? 0 : getSheetname().hashCode());
        result = prime * result + ((getMemname() == null) ? 0 : getMemname().hashCode());
        result = prime * result + ((getMemcard() == null) ? 0 : getMemcard().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getBizname() == null) ? 0 : getBizname().hashCode());
        result = prime * result + ((getMemmobile() == null) ? 0 : getMemmobile().hashCode());
        result = prime * result + ((getOccurpoints() == null) ? 0 : getOccurpoints().hashCode());
        result = prime * result + ((getPoints() == null) ? 0 : getPoints().hashCode());
        result = prime * result + ((getDirection() == null) ? 0 : getDirection().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", number=").append(number);
        sb.append(", sheetname=").append(sheetname);
        sb.append(", memname=").append(memname);
        sb.append(", memcard=").append(memcard);
        sb.append(", createtime=").append(createtime);
        sb.append(", bizname=").append(bizname);
        sb.append(", memmobile=").append(memmobile);
        sb.append(", occurpoints=").append(occurpoints);
        sb.append(", points=").append(points);
        sb.append(", direction=").append(direction);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}