package com.dhsy.async.mapper;

import com.dhsy.async.entity.PointFlow;
import com.dhsy.async.entity.PointFlowCriteria.Criteria;
import com.dhsy.async.entity.PointFlowCriteria.Criterion;
import com.dhsy.async.entity.PointFlowCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class PointFlowSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String countByExample(PointFlowCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("point_flow");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String deleteByExample(PointFlowCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("point_flow");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String insertSelective(PointFlow record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("point_flow");
        
        if (record.getNumber() != null) {
            sql.VALUES("number", "#{number,jdbcType=VARCHAR}");
        }
        
        if (record.getSheetname() != null) {
            sql.VALUES("sheetName", "#{sheetname,jdbcType=VARCHAR}");
        }
        
        if (record.getMemname() != null) {
            sql.VALUES("memName", "#{memname,jdbcType=VARCHAR}");
        }
        
        if (record.getMemcard() != null) {
            sql.VALUES("memCard", "#{memcard,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.VALUES("createTime", "#{createtime,jdbcType=DATE}");
        }
        
        if (record.getBizname() != null) {
            sql.VALUES("bizName", "#{bizname,jdbcType=VARCHAR}");
        }
        
        if (record.getMemmobile() != null) {
            sql.VALUES("memMobile", "#{memmobile,jdbcType=VARCHAR}");
        }
        
        if (record.getOccurpoints() != null) {
            sql.VALUES("occurPoints", "#{occurpoints,jdbcType=DECIMAL}");
        }
        
        if (record.getPoints() != null) {
            sql.VALUES("points", "#{points,jdbcType=DECIMAL}");
        }
        
        if (record.getDirection() != null) {
            sql.VALUES("direction", "#{direction,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String selectByExample(PointFlowCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("number");
        } else {
            sql.SELECT("number");
        }
        sql.SELECT("sheetName");
        sql.SELECT("memName");
        sql.SELECT("memCard");
        sql.SELECT("createTime");
        sql.SELECT("bizName");
        sql.SELECT("memMobile");
        sql.SELECT("occurPoints");
        sql.SELECT("points");
        sql.SELECT("direction");
        sql.SELECT("status");
        sql.FROM("point_flow");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        PointFlow record = (PointFlow) parameter.get("record");
        PointFlowCriteria example = (PointFlowCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("point_flow");
        
        if (record.getNumber() != null) {
            sql.SET("number = #{record.number,jdbcType=VARCHAR}");
        }
        
        if (record.getSheetname() != null) {
            sql.SET("sheetName = #{record.sheetname,jdbcType=VARCHAR}");
        }
        
        if (record.getMemname() != null) {
            sql.SET("memName = #{record.memname,jdbcType=VARCHAR}");
        }
        
        if (record.getMemcard() != null) {
            sql.SET("memCard = #{record.memcard,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("createTime = #{record.createtime,jdbcType=DATE}");
        }
        
        if (record.getBizname() != null) {
            sql.SET("bizName = #{record.bizname,jdbcType=VARCHAR}");
        }
        
        if (record.getMemmobile() != null) {
            sql.SET("memMobile = #{record.memmobile,jdbcType=VARCHAR}");
        }
        
        if (record.getOccurpoints() != null) {
            sql.SET("occurPoints = #{record.occurpoints,jdbcType=DECIMAL}");
        }
        
        if (record.getPoints() != null) {
            sql.SET("points = #{record.points,jdbcType=DECIMAL}");
        }
        
        if (record.getDirection() != null) {
            sql.SET("direction = #{record.direction,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{record.status,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("point_flow");
        
        sql.SET("number = #{record.number,jdbcType=VARCHAR}");
        sql.SET("sheetName = #{record.sheetname,jdbcType=VARCHAR}");
        sql.SET("memName = #{record.memname,jdbcType=VARCHAR}");
        sql.SET("memCard = #{record.memcard,jdbcType=VARCHAR}");
        sql.SET("createTime = #{record.createtime,jdbcType=DATE}");
        sql.SET("bizName = #{record.bizname,jdbcType=VARCHAR}");
        sql.SET("memMobile = #{record.memmobile,jdbcType=VARCHAR}");
        sql.SET("occurPoints = #{record.occurpoints,jdbcType=DECIMAL}");
        sql.SET("points = #{record.points,jdbcType=DECIMAL}");
        sql.SET("direction = #{record.direction,jdbcType=VARCHAR}");
        sql.SET("status = #{record.status,jdbcType=INTEGER}");
        
        PointFlowCriteria example = (PointFlowCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    public String updateByPrimaryKeySelective(PointFlow record) {
        SQL sql = new SQL();
        sql.UPDATE("point_flow");
        
        if (record.getSheetname() != null) {
            sql.SET("sheetName = #{sheetname,jdbcType=VARCHAR}");
        }
        
        if (record.getMemname() != null) {
            sql.SET("memName = #{memname,jdbcType=VARCHAR}");
        }
        
        if (record.getMemcard() != null) {
            sql.SET("memCard = #{memcard,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("createTime = #{createtime,jdbcType=DATE}");
        }
        
        if (record.getBizname() != null) {
            sql.SET("bizName = #{bizname,jdbcType=VARCHAR}");
        }
        
        if (record.getMemmobile() != null) {
            sql.SET("memMobile = #{memmobile,jdbcType=VARCHAR}");
        }
        
        if (record.getOccurpoints() != null) {
            sql.SET("occurPoints = #{occurpoints,jdbcType=DECIMAL}");
        }
        
        if (record.getPoints() != null) {
            sql.SET("points = #{points,jdbcType=DECIMAL}");
        }
        
        if (record.getDirection() != null) {
            sql.SET("direction = #{direction,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=INTEGER}");
        }
        
        sql.WHERE("number = #{number,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_flow
     *
     * @mbg.generated Wed May 08 14:50:48 CST 2019
     */
    protected void applyWhere(SQL sql, PointFlowCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}